// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbQZlNbJ-uGNUeQUR9pqf_C_5HVWU_K8E',
    appId: '1:70769982650:web:25ef71920eb32569071683',
    messagingSenderId: '70769982650',
    projectId: 'loan-app-cb7d2',
    authDomain: 'loan-app-cb7d2.firebaseapp.com',
    storageBucket: 'loan-app-cb7d2.firebasestorage.app',
    measurementId: 'G-Y8GEVF6W6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChGKmSLh8af1q7cHuCgJl0Uc5h-g5DK1c',
    appId: '1:70769982650:android:cb7efc9b509f15bb071683',
    messagingSenderId: '70769982650',
    projectId: 'loan-app-cb7d2',
    storageBucket: 'loan-app-cb7d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXKnxStYtVOg81oWmQhwIj-g7EOHmxSyc',
    appId: '1:70769982650:ios:cfc61151b2c35e63071683',
    messagingSenderId: '70769982650',
    projectId: 'loan-app-cb7d2',
    storageBucket: 'loan-app-cb7d2.firebasestorage.app',
    iosClientId: '70769982650-4dms4dfn0o3v4qokold6gmmh66bg0ocf.apps.googleusercontent.com',
    iosBundleId: 'com.example.theloanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbQZlNbJ-uGNUeQUR9pqf_C_5HVWU_K8E',
    appId: '1:70769982650:web:f8bf3196c8ca9a10071683',
    messagingSenderId: '70769982650',
    projectId: 'loan-app-cb7d2',
    authDomain: 'loan-app-cb7d2.firebaseapp.com',
    storageBucket: 'loan-app-cb7d2.firebasestorage.app',
    measurementId: 'G-ZCJSRW62K1',
  );
}
